server:
  port: 9002
  tomcat:
    threads:
      max: 50
      min-spare: 5
    connection-timeout: 2s
    keep-alive-timeout: 15s

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ctientcheu/config-repo
          timeout: 5
          clone-on-start: true
          force-pull: true
          default-label: master
